# Generated by Django 2.2.1 on 2020-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('createtime', models.DateField(auto_now=True)),
            ],
        ),
    ]
