# Generated by Django 2.2.1 on 2020-08-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0002_auto_20200802_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_home_herf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('herf', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
