# Generated by Django 2.2.1 on 2020-08-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0003_db_home_herf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_home_herf',
            new_name='DB_home_href',
        ),
        migrations.RenameField(
            model_name='db_home_href',
            old_name='herf',
            new_name='href',
        ),
    ]
